
# Resource
spring:
  profiles: local

# Mysql DataBase
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/testdb
    username: testuser
    password: testuser123